apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_USER: todouser
  POSTGRES_PASSWORD: supersecret123
  POSTGRES_DB: tododb
  DB_USER: todouser
  DB_PASSWORD: supersecret123
